/*
 * AProposJFrame.java
 *
 * Created on 26 octobre 2006, 21:13
 */

package JRaw.ihm;

import javax.swing.JFrame;

/**
 *
 * @author  YvesFabienne
 */
public class AProposJFrame extends javax.swing.JDialog {
    
    /** Creates new form AProposJFrame */
    public AProposJFrame(JFrame owner) {
        super( owner, true);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        okjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A propos de JRaw...");
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JRaw Version 3.6");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 30, 330, 14);

        okjButton.setText("OK");
        okjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okjButton);
        okjButton.setBounds(137, 140, 70, 23);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Yves BOYADJIAN 2012");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 70, 340, 14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Site : http://yboyadjian.free.fr");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-1, 90, 340, 14);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-347)/2, (screenSize.height-234)/2, 347, 234);
    }// </editor-fold>//GEN-END:initComponents

    private void okjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okjButtonActionPerformed
// add your handling code here:
        setVisible( false);
        dispose();
    }//GEN-LAST:event_okjButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AProposJFrame(null).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton okjButton;
    // End of variables declaration//GEN-END:variables
    
}
