/*
 * ModeEmploiJFrame.java
 *
 * Created on 25 novembre 2007, 14:19
 */

package JRaw.ihm;

import javax.swing.JFrame;

/**
 *
 * @author  YvesFabienne
 */
public class ModeEmploiJFrame extends javax.swing.JDialog {
    
    /** Creates new form ModeEmploiJFrame */
    public ModeEmploiJFrame(JFrame owner) {
        super( owner, true);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("JRaw/jraw"); // NOI18N
        setTitle(bundle.getString("mode_d_emploi_")); // NOI18N

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 300));
        jScrollPane1.setRequestFocusEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Vous pouvez ouvrir un fichier RAW par Drag and Drop.\n\nPour passer en mode plein écran, appuyer sur F11 \nou double-cliquer sur l'image.\nPour revenir au mode normal, réappuyer sur F11\nou double-cliquer sur l'image.\n\nPour de meilleures performances, sélectionner\nle nombre de cores égal au nombre de cores de \nvotre processeur.\n\nCliquer sur \"expo +\" ou \"expo -\" pour augmenter\nou diminuer le contraste de l'image d'un tiers\nd'EV.\n\nCliquer sur \"Daylight\" ou \"Tungstene\" pour changer\nla balance des blancs ( nota: Cette fonction n'est \nactive que si le fichier raw ne comporte pas\nde balance des blancs intégrée.)\n\nLe menu \"Compression\" vous permet de choisir entre\n3 niveaux  différents de compression, \"Stockage\"\npour la meilleure qualité, \"Internet\" pour\nenvoyer des photos par mail, et le mode \"Taille Réduite\"\npermet de réduire la résolution de la photo si \ncelle-ci est très bruitée. Le taux de compression \nest ajusté de manière à avoir une taille de 500K.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// add your handling code here:
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModeEmploiJFrame(null).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
}
